// Code generated by protoc-gen-go. DO NOT EDIT.
// source: archiver.proto

/*
Package practical_grpc_v1 is a generated protocol buffer package.

It is generated from these files:
	archiver.proto

It has these top-level messages:
	SearchRequest
	SearchResponse
	ZipRequest
	ZipResponse
*/
package practical_grpc_v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SearchRequest struct {
	Term       string `protobuf:"bytes,1,opt,name=term" json:"term,omitempty"`
	MaxResults int64  `protobuf:"varint,2,opt,name=max_results,json=maxResults" json:"max_results,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SearchRequest) GetTerm() string {
	if m != nil {
		return m.Term
	}
	return ""
}

func (m *SearchRequest) GetMaxResults() int64 {
	if m != nil {
		return m.MaxResults
	}
	return 0
}

type SearchResponse struct {
	MatchedTerm string `protobuf:"bytes,1,opt,name=matched_term,json=matchedTerm" json:"matched_term,omitempty"`
	Content     string `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
	Rank        int32  `protobuf:"varint,3,opt,name=rank" json:"rank,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SearchResponse) GetMatchedTerm() string {
	if m != nil {
		return m.MatchedTerm
	}
	return ""
}

func (m *SearchResponse) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *SearchResponse) GetRank() int32 {
	if m != nil {
		return m.Rank
	}
	return 0
}

type ZipRequest struct {
	FileName string `protobuf:"bytes,1,opt,name=file_name,json=fileName" json:"file_name,omitempty"`
	Contents []byte `protobuf:"bytes,2,opt,name=contents,proto3" json:"contents,omitempty"`
}

func (m *ZipRequest) Reset()                    { *m = ZipRequest{} }
func (m *ZipRequest) String() string            { return proto.CompactTextString(m) }
func (*ZipRequest) ProtoMessage()               {}
func (*ZipRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ZipRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *ZipRequest) GetContents() []byte {
	if m != nil {
		return m.Contents
	}
	return nil
}

type ZipResponse struct {
	ZippedContents []byte `protobuf:"bytes,1,opt,name=zipped_contents,json=zippedContents,proto3" json:"zipped_contents,omitempty"`
}

func (m *ZipResponse) Reset()                    { *m = ZipResponse{} }
func (m *ZipResponse) String() string            { return proto.CompactTextString(m) }
func (*ZipResponse) ProtoMessage()               {}
func (*ZipResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ZipResponse) GetZippedContents() []byte {
	if m != nil {
		return m.ZippedContents
	}
	return nil
}

func init() {
	proto.RegisterType((*SearchRequest)(nil), "practical.grpc.v1.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "practical.grpc.v1.SearchResponse")
	proto.RegisterType((*ZipRequest)(nil), "practical.grpc.v1.ZipRequest")
	proto.RegisterType((*ZipResponse)(nil), "practical.grpc.v1.ZipResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Database service

type DatabaseClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (Database_SearchClient, error)
}

type databaseClient struct {
	cc *grpc.ClientConn
}

func NewDatabaseClient(cc *grpc.ClientConn) DatabaseClient {
	return &databaseClient{cc}
}

func (c *databaseClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (Database_SearchClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Database_serviceDesc.Streams[0], c.cc, "/practical.grpc.v1.Database/Search", opts...)
	if err != nil {
		return nil, err
	}
	x := &databaseSearchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Database_SearchClient interface {
	Recv() (*SearchResponse, error)
	grpc.ClientStream
}

type databaseSearchClient struct {
	grpc.ClientStream
}

func (x *databaseSearchClient) Recv() (*SearchResponse, error) {
	m := new(SearchResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Database service

type DatabaseServer interface {
	Search(*SearchRequest, Database_SearchServer) error
}

func RegisterDatabaseServer(s *grpc.Server, srv DatabaseServer) {
	s.RegisterService(&_Database_serviceDesc, srv)
}

func _Database_Search_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DatabaseServer).Search(m, &databaseSearchServer{stream})
}

type Database_SearchServer interface {
	Send(*SearchResponse) error
	grpc.ServerStream
}

type databaseSearchServer struct {
	grpc.ServerStream
}

func (x *databaseSearchServer) Send(m *SearchResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Database_serviceDesc = grpc.ServiceDesc{
	ServiceName: "practical.grpc.v1.Database",
	HandlerType: (*DatabaseServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Search",
			Handler:       _Database_Search_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "archiver.proto",
}

// Client API for Archiver service

type ArchiverClient interface {
	Zip(ctx context.Context, opts ...grpc.CallOption) (Archiver_ZipClient, error)
}

type archiverClient struct {
	cc *grpc.ClientConn
}

func NewArchiverClient(cc *grpc.ClientConn) ArchiverClient {
	return &archiverClient{cc}
}

func (c *archiverClient) Zip(ctx context.Context, opts ...grpc.CallOption) (Archiver_ZipClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Archiver_serviceDesc.Streams[0], c.cc, "/practical.grpc.v1.Archiver/Zip", opts...)
	if err != nil {
		return nil, err
	}
	x := &archiverZipClient{stream}
	return x, nil
}

type Archiver_ZipClient interface {
	Send(*ZipRequest) error
	CloseAndRecv() (*ZipResponse, error)
	grpc.ClientStream
}

type archiverZipClient struct {
	grpc.ClientStream
}

func (x *archiverZipClient) Send(m *ZipRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *archiverZipClient) CloseAndRecv() (*ZipResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ZipResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Archiver service

type ArchiverServer interface {
	Zip(Archiver_ZipServer) error
}

func RegisterArchiverServer(s *grpc.Server, srv ArchiverServer) {
	s.RegisterService(&_Archiver_serviceDesc, srv)
}

func _Archiver_Zip_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ArchiverServer).Zip(&archiverZipServer{stream})
}

type Archiver_ZipServer interface {
	SendAndClose(*ZipResponse) error
	Recv() (*ZipRequest, error)
	grpc.ServerStream
}

type archiverZipServer struct {
	grpc.ServerStream
}

func (x *archiverZipServer) SendAndClose(m *ZipResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *archiverZipServer) Recv() (*ZipRequest, error) {
	m := new(ZipRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Archiver_serviceDesc = grpc.ServiceDesc{
	ServiceName: "practical.grpc.v1.Archiver",
	HandlerType: (*ArchiverServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Zip",
			Handler:       _Archiver_Zip_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "archiver.proto",
}

func init() { proto.RegisterFile("archiver.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 306 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x4f, 0x4f, 0xc2, 0x40,
	0x10, 0xc5, 0xb3, 0xa2, 0x58, 0x06, 0xc4, 0xb8, 0xa7, 0x06, 0xa3, 0x96, 0x5e, 0xec, 0xa9, 0x51,
	0x4c, 0xbc, 0x1b, 0xd1, 0xa3, 0x26, 0xab, 0x27, 0x3c, 0x34, 0x43, 0x19, 0xa5, 0x91, 0xb6, 0xeb,
	0x76, 0x21, 0xc4, 0x4f, 0x6f, 0xba, 0xbb, 0x45, 0x8d, 0x7f, 0x6e, 0x3b, 0x6f, 0xe7, 0xfd, 0xf2,
	0x66, 0x06, 0xfa, 0xa8, 0xd2, 0x79, 0xb6, 0x22, 0x15, 0x4b, 0x55, 0xea, 0x92, 0x1f, 0x48, 0x85,
	0xa9, 0xce, 0x52, 0x5c, 0xc4, 0x2f, 0x4a, 0xa6, 0xf1, 0xea, 0x3c, 0x1c, 0xc3, 0xde, 0x03, 0xd5,
	0x6d, 0x82, 0xde, 0x96, 0x54, 0x69, 0xce, 0x61, 0x5b, 0x93, 0xca, 0x7d, 0x16, 0xb0, 0xa8, 0x23,
	0xcc, 0x9b, 0x9f, 0x40, 0x37, 0xc7, 0x75, 0xa2, 0xa8, 0x5a, 0x2e, 0x74, 0xe5, 0x6f, 0x05, 0x2c,
	0x6a, 0x09, 0xc8, 0x71, 0x2d, 0xac, 0x12, 0x22, 0xf4, 0x1b, 0x4a, 0x25, 0xcb, 0xa2, 0x22, 0x3e,
	0x84, 0x5e, 0x8e, 0x3a, 0x9d, 0xd3, 0x2c, 0xf9, 0x82, 0xeb, 0x3a, 0xed, 0xb1, 0xa6, 0xfa, 0xb0,
	0x9b, 0x96, 0x85, 0xa6, 0x42, 0x1b, 0x62, 0x47, 0x34, 0x65, 0x9d, 0x41, 0x61, 0xf1, 0xea, 0xb7,
	0x02, 0x16, 0xed, 0x08, 0xf3, 0x0e, 0x6f, 0x00, 0x26, 0x99, 0x6c, 0x52, 0x1e, 0x42, 0xe7, 0x39,
	0x5b, 0x50, 0x52, 0x60, 0x4e, 0x8e, 0xed, 0xd5, 0xc2, 0x1d, 0xe6, 0xc4, 0x07, 0xe0, 0x39, 0x92,
	0xcd, 0xda, 0x13, 0x9b, 0x3a, 0xbc, 0x84, 0xae, 0xc1, 0xb8, 0x98, 0xa7, 0xb0, 0xff, 0x9e, 0x49,
	0x49, 0xb3, 0x64, 0xe3, 0x60, 0xc6, 0xd1, 0xb7, 0xf2, 0xb5, 0x53, 0x47, 0x4f, 0xe0, 0x8d, 0x51,
	0xe3, 0x14, 0x2b, 0xe2, 0xf7, 0xd0, 0xb6, 0xd3, 0xf2, 0x20, 0xfe, 0xb1, 0xd1, 0xf8, 0xdb, 0x3a,
	0x07, 0xc3, 0x7f, 0x3a, 0x6c, 0x86, 0x33, 0x36, 0x12, 0xe0, 0x5d, 0xb9, 0x4b, 0xf1, 0x5b, 0x68,
	0x4d, 0x32, 0xc9, 0x8f, 0x7e, 0xf1, 0x7d, 0xce, 0x3f, 0x38, 0xfe, 0xeb, 0xdb, 0x32, 0x23, 0x36,
	0x6d, 0x9b, 0x93, 0x5f, 0x7c, 0x04, 0x00, 0x00, 0xff, 0xff, 0xab, 0xcf, 0x30, 0xc7, 0x04, 0x02,
	0x00, 0x00,
}
