# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/archiver.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/archiver.proto',
  package='practical.grpc.v1',
  syntax='proto3',
  serialized_pb=_b('\n\x14proto/archiver.proto\x12\x11practical.grpc.v1\"2\n\rSearchRequest\x12\x0c\n\x04term\x18\x01 \x01(\t\x12\x13\n\x0bmax_results\x18\x02 \x01(\x03\"E\n\x0eSearchResponse\x12\x14\n\x0cmatched_term\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x0c\n\x04rank\x18\x03 \x01(\x05\"1\n\nZipRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x10\n\x08\x63ontents\x18\x02 \x01(\x0c\"&\n\x0bZipResponse\x12\x17\n\x0fzipped_contents\x18\x01 \x01(\x0c\x32[\n\x08\x44\x61tabase\x12O\n\x06Search\x12 .practical.grpc.v1.SearchRequest\x1a!.practical.grpc.v1.SearchResponse0\x01\x32R\n\x08\x41rchiver\x12\x46\n\x03Zip\x12\x1d.practical.grpc.v1.ZipRequest\x1a\x1e.practical.grpc.v1.ZipResponse(\x01\x62\x06proto3')
)




_SEARCHREQUEST = _descriptor.Descriptor(
  name='SearchRequest',
  full_name='practical.grpc.v1.SearchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='term', full_name='practical.grpc.v1.SearchRequest.term', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_results', full_name='practical.grpc.v1.SearchRequest.max_results', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=93,
)


_SEARCHRESPONSE = _descriptor.Descriptor(
  name='SearchResponse',
  full_name='practical.grpc.v1.SearchResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='matched_term', full_name='practical.grpc.v1.SearchResponse.matched_term', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='practical.grpc.v1.SearchResponse.content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rank', full_name='practical.grpc.v1.SearchResponse.rank', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=164,
)


_ZIPREQUEST = _descriptor.Descriptor(
  name='ZipRequest',
  full_name='practical.grpc.v1.ZipRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_name', full_name='practical.grpc.v1.ZipRequest.file_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='contents', full_name='practical.grpc.v1.ZipRequest.contents', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=215,
)


_ZIPRESPONSE = _descriptor.Descriptor(
  name='ZipResponse',
  full_name='practical.grpc.v1.ZipResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='zipped_contents', full_name='practical.grpc.v1.ZipResponse.zipped_contents', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=255,
)

DESCRIPTOR.message_types_by_name['SearchRequest'] = _SEARCHREQUEST
DESCRIPTOR.message_types_by_name['SearchResponse'] = _SEARCHRESPONSE
DESCRIPTOR.message_types_by_name['ZipRequest'] = _ZIPREQUEST
DESCRIPTOR.message_types_by_name['ZipResponse'] = _ZIPRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SearchRequest = _reflection.GeneratedProtocolMessageType('SearchRequest', (_message.Message,), dict(
  DESCRIPTOR = _SEARCHREQUEST,
  __module__ = 'proto.archiver_pb2'
  # @@protoc_insertion_point(class_scope:practical.grpc.v1.SearchRequest)
  ))
_sym_db.RegisterMessage(SearchRequest)

SearchResponse = _reflection.GeneratedProtocolMessageType('SearchResponse', (_message.Message,), dict(
  DESCRIPTOR = _SEARCHRESPONSE,
  __module__ = 'proto.archiver_pb2'
  # @@protoc_insertion_point(class_scope:practical.grpc.v1.SearchResponse)
  ))
_sym_db.RegisterMessage(SearchResponse)

ZipRequest = _reflection.GeneratedProtocolMessageType('ZipRequest', (_message.Message,), dict(
  DESCRIPTOR = _ZIPREQUEST,
  __module__ = 'proto.archiver_pb2'
  # @@protoc_insertion_point(class_scope:practical.grpc.v1.ZipRequest)
  ))
_sym_db.RegisterMessage(ZipRequest)

ZipResponse = _reflection.GeneratedProtocolMessageType('ZipResponse', (_message.Message,), dict(
  DESCRIPTOR = _ZIPRESPONSE,
  __module__ = 'proto.archiver_pb2'
  # @@protoc_insertion_point(class_scope:practical.grpc.v1.ZipResponse)
  ))
_sym_db.RegisterMessage(ZipResponse)



_DATABASE = _descriptor.ServiceDescriptor(
  name='Database',
  full_name='practical.grpc.v1.Database',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=257,
  serialized_end=348,
  methods=[
  _descriptor.MethodDescriptor(
    name='Search',
    full_name='practical.grpc.v1.Database.Search',
    index=0,
    containing_service=None,
    input_type=_SEARCHREQUEST,
    output_type=_SEARCHRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATABASE)

DESCRIPTOR.services_by_name['Database'] = _DATABASE


_ARCHIVER = _descriptor.ServiceDescriptor(
  name='Archiver',
  full_name='practical.grpc.v1.Archiver',
  file=DESCRIPTOR,
  index=1,
  options=None,
  serialized_start=350,
  serialized_end=432,
  methods=[
  _descriptor.MethodDescriptor(
    name='Zip',
    full_name='practical.grpc.v1.Archiver.Zip',
    index=0,
    containing_service=None,
    input_type=_ZIPREQUEST,
    output_type=_ZIPRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ARCHIVER)

DESCRIPTOR.services_by_name['Archiver'] = _ARCHIVER

# @@protoc_insertion_point(module_scope)
